export const data = JSON.parse("{\"key\":\"v-eac11492\",\"path\":\"/demo/algorithm/%E5%8F%98%E9%87%8F%E3%80%81%E8%A1%A8%E8%BE%BE%E5%BC%8F%E4%B8%8E%E9%A1%BA%E5%BA%8F%E8%AF%AD%E5%8F%A5.html\",\"title\":\"\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"变量 理解：程序中存储信息的一个盒子（空间） 类型： bool、char、int、float、double、long long、long double 输入与输出 c++输入输出为：cin与cout c语言输入输出为：scanf()与printf 输入大数据时，采用scanf、printf更加节省时间，但是也可以关闭iostream缓存流运用cin cout输入输出大数据（关闭后cin cout不可与scanf printf混用）\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/demo/algorithm/%E5%8F%98%E9%87%8F%E3%80%81%E8%A1%A8%E8%BE%BE%E5%BC%8F%E4%B8%8E%E9%A1%BA%E5%BA%8F%E8%AF%AD%E5%8F%A5.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"EasonYF\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"变量 理解：程序中存储信息的一个盒子（空间） 类型： bool、char、int、float、double、long long、long double 输入与输出 c++输入输出为：cin与cout c语言输入输出为：scanf()与printf 输入大数据时，采用scanf、printf更加节省时间，但是也可以关闭iostream缓存流运用cin cout输入输出大数据（关闭后cin cout不可与scanf printf混用）\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Mr.YF\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Mr.YF\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"变量\",\"slug\":\"变量\",\"link\":\"#变量\",\"children\":[{\"level\":3,\"title\":\"理解：程序中存储信息的一个盒子（空间）\",\"slug\":\"理解-程序中存储信息的一个盒子-空间\",\"link\":\"#理解-程序中存储信息的一个盒子-空间\",\"children\":[]},{\"level\":3,\"title\":\"类型：\",\"slug\":\"类型\",\"link\":\"#类型\",\"children\":[]}]},{\"level\":2,\"title\":\"输入与输出\",\"slug\":\"输入与输出\",\"link\":\"#输入与输出\",\"children\":[]},{\"level\":2,\"title\":\"表达式\",\"slug\":\"表达式\",\"link\":\"#表达式\",\"children\":[]}],\"readingTime\":{\"minutes\":1.1,\"words\":331},\"filePathRelative\":\"demo/algorithm/变量、表达式与顺序语句.md\",\"excerpt\":\"<h2> 变量</h2>\\n<h3> 理解：程序中存储信息的一个盒子（空间）</h3>\\n<h3> 类型：</h3>\\n<ul>\\n<li><code>bool、char、int、float、double、long long、long double</code></li>\\n</ul>\\n<h2> 输入与输出</h2>\\n<ul>\\n<li>c++输入输出为：<code>cin与cout</code></li>\\n<li>c语言输入输出为：<code>scanf()与printf</code></li>\\n<li>输入大数据时，采用scanf、printf更加节省时间，但是也可以关闭<code>iostream</code>缓存流运用<code>cin cout</code>输入输出大数据（关闭后<code>cin cout</code>不可与<code>scanf printf</code>混用）</li>\\n</ul>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
