export const data = JSON.parse("{\"key\":\"v-15f64fce\",\"path\":\"/demo/front-end/ajax/%E8%B7%A8%E5%9F%9F%E5%92%8CJSONP.html\",\"title\":\"同源策略和跨域\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"同源策略和跨域\",\"icon\":\"write\",\"category\":[\"前端\"],\"tag\":[\"前端\"],\"sticky\":false,\"star\":false,\"article\":true,\"timeline\":true,\"description\":\"同源策略和跨域 同源策略 同源：如果两个页面的协议、域名和端口都相同则两个页面具有相同的源 image.png 同源策略：是浏览器提供的一个安全功能 ，同源策略限制了从同一个源加载的文档或脚本如何与来着另一个源的资源进行交互。这是一个用于隔离潜在恶意文件的重要安全机制\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/demo/front-end/ajax/%E8%B7%A8%E5%9F%9F%E5%92%8CJSONP.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"EasonYF\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"同源策略和跨域\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"同源策略和跨域 同源策略 同源：如果两个页面的协议、域名和端口都相同则两个页面具有相同的源 image.png 同源策略：是浏览器提供的一个安全功能 ，同源策略限制了从同一个源加载的文档或脚本如何与来着另一个源的资源进行交互。这是一个用于隔离潜在恶意文件的重要安全机制\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Mr.YF\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"前端\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"同源策略和跨域\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Mr.YF\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"同源策略和跨域\",\"slug\":\"同源策略和跨域\",\"link\":\"#同源策略和跨域\",\"children\":[{\"level\":3,\"title\":\"同源策略\",\"slug\":\"同源策略\",\"link\":\"#同源策略\",\"children\":[]},{\"level\":3,\"title\":\"跨域\",\"slug\":\"跨域\",\"link\":\"#跨域\",\"children\":[]}]},{\"level\":2,\"title\":\"JSONP\",\"slug\":\"jsonp\",\"link\":\"#jsonp\",\"children\":[{\"level\":3,\"title\":\"实现原理\",\"slug\":\"实现原理\",\"link\":\"#实现原理\",\"children\":[]}]}],\"readingTime\":{\"minutes\":2.26,\"words\":677},\"filePathRelative\":\"demo/front-end/ajax/跨域和JSONP.md\",\"excerpt\":\"<h2> 同源策略和跨域</h2>\\n<h3> 同源策略</h3>\\n<ul>\\n<li>同源：如果两个页面的协议、域名和端口都相同则两个页面具有相同的源</li>\\n<li><img src=\\\"https://cdn.nlark.com/yuque/0/2023/png/35273604/1685946116761-ffa704ff-a411-4f90-8c54-aa5e67e33dd7.png#averageHue=%23b9d2e9&amp;clientId=u0c5b7443-bfaf-4&amp;from=paste&amp;height=293&amp;id=u32b998eb&amp;originHeight=440&amp;originWidth=1541&amp;originalType=binary&amp;ratio=1.5&amp;rotation=0&amp;showTitle=false&amp;size=384642&amp;status=done&amp;style=none&amp;taskId=uec6454c7-4548-4a64-a5e8-0595865c3f1&amp;title=&amp;width=1027.3333333333333\\\" alt=\\\"image.png\\\" tabindex=\\\"0\\\" loading=\\\"lazy\\\"><figcaption>image.png</figcaption></li>\\n<li>同源策略：是浏览器提供的一个安全功能 ，同源策略限制了从同一个源加载的文档或脚本如何与来着另一个源的资源进行交互。这是一个用于隔离潜在恶意文件的重要安全机制</li>\\n</ul>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
